### ISSUE TITLE
What is your library suppose to do? Can you explain it? Thank you so much.

### ISSUE THREAD

**Issue by ducpt2** [Yoctol/react-messenger-checkbox#3]
What is your library suppose to do? Can you explain it? Thank you so much.

**Comment by tw0517tw** [comment]
as [README.md](https://github.com/Yoctol/react-messenger-checkbox#react-messenger-checkbox) says:
> React component for Messenger checkbox plugin

**Comment by ducpt2** [comment]
@tw0517tw so you mean that it set whitelist domain?
